version: "3"

services:
  backend:
    container_name: backend
    build:
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend
